/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AltJTalkConfig {
  dictionary: string
  model: string
}
export class AltJTalk {
  static fromConfig(config: AltJTalkConfig): AltJTalk
  synthesize(inputText: string): Int16Array
}
